# -*- coding: utf-8 -*-
"""Regenerate app ExtraPrompts.kt from material_yard/harvest/prompts_*.json.

Rebuilt 2026-07-14 (original generate_extra_prompts.ps1 lives on another machine,
material_yard is not in git). Output format must stay byte-identical to the
established ExtraPrompts.kt layout — verify with --check before committing.

Usage:
  py tools/generate_extra_prompts.py                 # regenerate ExtraPrompts.kt
  py tools/generate_extra_prompts.py --check         # regenerate to stdout-diff only (no write)
  py tools/generate_extra_prompts.py --max-pack 11   # only packs <= N (for verifying against old output)
"""
import argparse
import glob
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_HARVEST = os.path.normpath(os.path.join(REPO, "..", "..", "material_yard", "harvest"))
OUT = os.path.join(
    REPO, "app", "src", "main", "kotlin", "com", "za869765", "imagine",
    "ui", "component", "ExtraPrompts.kt",
)

HEADER = """package com.za869765.imagine.ui.component

// AUTO-GENERATED by tools/generate_extra_prompts.py from material_yard/harvest/prompts_*.json.
// Material prompt packs: three-view / fight / micro-expression / scene+style / …
// Same schema as READY_PROMPTS. Consumers use (READY_PROMPTS + EXTRA_PROMPTS).
// To edit prompts: change the JSON and re-run the script. Do NOT hand-edit this file.
val EXTRA_PROMPTS: List<PromptExample> = listOf(
"""

# Historical header (what the .ps1 emitted) — used with --legacy-header to verify
# byte-identity against the committed file before this script existed.
LEGACY_HEADER = """package com.za869765.imagine.ui.component

// AUTO-GENERATED by material_yard/tools/generate_extra_prompts.ps1 from harvest prompts_*.json.
// Material prompt packs: three-view / fight / micro-expression / scene+style.
// Same schema as READY_PROMPTS. Consumers use (READY_PROMPTS + EXTRA_PROMPTS).
// To edit prompts: change the JSON and re-run the script. Do NOT hand-edit this file.
val EXTRA_PROMPTS: List<PromptExample> = listOf(
"""


def kt_escape(s: str) -> str:
    s = s.replace("\\", "\\\\").replace("\"", "\\\"")
    s = s.replace("$", "${'$'}")
    s = s.replace("\r\n", "\\n").replace("\n", "\\n").replace("\r", "\\n")
    s = s.replace("\t", "\\t").replace("\b", "\\b").replace("\f", "\\u000c")
    return s


def pack_number(path: str) -> int:
    m = re.search(r"prompts_(\d+)", os.path.basename(path))
    return int(m.group(1)) if m else 999


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--harvest", default=DEFAULT_HARVEST)
    ap.add_argument("--max-pack", type=int, default=None)
    ap.add_argument("--check", action="store_true", help="compare against current file, do not write")
    ap.add_argument("--legacy-header", action="store_true")
    args = ap.parse_args()

    # NOTE: lexicographic filename order (prompts_0, 1, 10, 11, 12, …, 2, 3 …) —
    # this reproduces the original .ps1 (Get-ChildItem) ordering the app shipped with;
    # category capsule order in the UI derives from list order, keep it stable.
    # "_" must sort before digits (.NET culture sort) → replace "_" with space for the key,
    # giving 0, 1, 10, 11, 12, …, 2, 3 … exactly like the original output.
    files = sorted(
        glob.glob(os.path.join(args.harvest, "prompts_*.json")),
        key=lambda p: os.path.basename(p).replace("_", " "),
    )
    if args.max_pack is not None:
        files = [f for f in files if pack_number(f) <= args.max_pack]
    if not files:
        print("no prompts_*.json found in", args.harvest)
        return 1

    parts = [LEGACY_HEADER if args.legacy_header else HEADER]
    total = 0
    for path in files:
        with open(path, encoding="utf-8-sig") as fh:
            data = json.load(fh)
        for e in data:
            usage = e.get("usage", "")
            # Legacy packs (0/2) used usage "three-view" → these are t2i model sheets.
            if usage == "three-view":
                usage = "t2i"
            # Legacy packs used ASCII "-" for subcategory ("微表情-壞笑" → "微表情");
            # newer packs use "·" ("三視圖·海賊王") which is kept as-is.
            category = e.get("category", "").split("-")[0]
            for_video = "true" if usage in ("i2v", "t2v") else "false"
            parts.append("    PromptExample(\n")
            parts.append('        "%s",\n' % kt_escape(e["tag"]))
            parts.append('        "%s",\n' % kt_escape(e["text"]))
            parts.append("        forVideo = %s,\n" % for_video)
            parts.append('        category = "%s",\n' % kt_escape(category))
            parts.append('        usage = "%s",\n' % kt_escape(usage))
            parts.append("    ),\n")
            total += 1
    parts.append(")\n")
    output = "".join(parts)

    if args.check:
        with open(OUT, "rb") as fh:
            current_bytes = fh.read()
        if current_bytes == output.encode("utf-8"):
            print("IDENTICAL (%d entries)" % total)
            return 0
        current = current_bytes.decode("utf-8")
        cur_lines = current.splitlines()
        new_lines = output.splitlines()
        print("DIFFERS: current %d lines vs generated %d lines" % (len(cur_lines), len(new_lines)))
        for i, (a, b) in enumerate(zip(cur_lines, new_lines), 1):
            if a != b:
                print("first diff at line %d:" % i)
                print("  cur: %s" % a[:200])
                print("  new: %s" % b[:200])
                break
        return 2

    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(output)
    print("wrote %s (%d entries from %d packs)" % (OUT, total, len(files)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
